### ISSUE TITLE
Code folding doesn't work with multi-line raw strings

### ISSUE THREAD

**Issue by zmb3** [atom/language-go#101]
As the title says, code segments with multi-line raw strings can't be folded.
These such strings can make code hard to read as they mess with the indentation, so being able to hide areas where they occur would be helpful.

```
package main

func main() {
  fmt.Println(`This
is
a
multiline
string`)
}
```

Expected behavior when folding:
![image](https://cloud.githubusercontent.com/assets/7527103/20459147/c9996d2e-ae74-11e6-9b9a-a7639ecbd580.png)

Actual behavior:
![image](https://cloud.githubusercontent.com/assets/7527103/20459151/dae08914-ae74-11e6-86fc-a664984aaea0.png)

Seems related to #65 and https://github.com/atom/atom/issues/3442

**Comment by 50Wliu** [comment]
Closing in favor of atom/atom#3442.  language-go can't do anything about this until atom/atom#3442 is resolved.
