### ISSUE TITLE
Bug with in-line comments

### ISSUE THREAD

**Issue by Zamiell** [atom/language-go#102]
See attached picture. This should be easily reproducible.

![atombug](https://cloud.githubusercontent.com/assets/5511220/20534054/b8756486-b0ad-11e6-8828-d4ad4581b407.png)

**Comment by Zamiell** [comment]
![bug2](https://cloud.githubusercontent.com/assets/5511220/20534482/60d13a82-b0af-11e6-877b-71d3b1ad9083.png)

**Comment by joefitzgerald** [comment]
This is most likely a side effect of this: https://github.com/atom/language-go/pull/97

Would you have time to add a spec to replicate the failure and potentially fix it?

**Comment by Zamiell** [comment]
Sure, I'll give it a shot.

**Comment by Zamiell** [comment]
Can you give further instructions for how add the custom spec?

**Comment by joefitzgerald** [comment]
https://github.com/atom/language-go/blob/master/spec/go-spec.coffee; find the import specs.

**Comment by rumpelsepp** [comment]
There is also a bug when you comment out package imports like this:

```go
import (
    // foo
)
```

**Comment by 50Wliu** [comment]
Should be a trivial fix.  Will look into it.
