### ISSUE TITLE
Multi-line string highlighting with backtick

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#103]
_From @brandonblock on November 29, 2016 19:11_

When I paste a multiline string as a variable value and surround the string with a backtick, only the first line is highlighted. If I do a new line after the = the highlighting works but gofmt moves the value back to the same line as the assignment.

![screen shot 2016-11-29 at 13 11 14](https://cloud.githubusercontent.com/assets/2208544/20724818/5d49e658-b635-11e6-8e93-1abb15941d2d.png)

_Copied from original issue: Microsoft/vscode-go#666_

**Comment by xeger** [comment]
Furthermore, a multiline backtick string seems to cause errors in the highlighting of the rest of the file!
![capture d ecran 2016-12-14 a 12 34 12](https://cloud.githubusercontent.com/assets/73368/21199744/a8f66192-c1f9-11e6-81c6-579d4386ac65.png)

**Comment by rjboer** [comment]
have this as well:
(https://github.com/AtomLinter/linter-golinter/issues/95)

also works with (`

`)

**Comment by dramich** [comment]
Is there an update on this? I see there is an open pull request with a fix.

**Comment by 50Wliu** [comment]
Yep, it's not done yet.  I need to finish it up.

**Comment by ramya-rao-a** [comment]
@50Wliu I can still repro this in Atom (Version 1.15) 
Do we need to do anything specific as a user to get the latest grammar?
