### ISSUE TITLE
Comments in import block not getting the right color

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#119]
_From @zoobenthos on May 5, 2017 20:22_

The comments in import block is constant and terribly (as it looks) problem.
It sometimes works right in beginning of the comment line, but is not works right before the module string, etc
Sorry, but it is simply bullshit

_Copied from original issue: Microsoft/vscode-go#969_

**Comment by ramya-rao-a** [comment]
> The comments in import block is constant

What comments?

> It sometimes works right in beginning of the comment line,

What works right in the beginning of the comment line?

Your issue description is not clear.
Can you please elaborate?

**Comment by ramya-rao-a** [comment]
_From @zoobenthos on May 6, 2017 6:58_

In previous version this bug was partially fixed but in current version that is appears again.
![example](http://i.imgur.com/TIsDcI9.png)
Partially - because second comment example was not worked properly. Now is both not worked :)

**Comment by ramya-rao-a** [comment]
Thanks @zoobenthos 
We will look into this.

**Comment by ramya-rao-a** [comment]
Below is a side-by-side comparison of the same code in atom and vscode

The import paths are commented, they don't get the right color.

When inspecting the scope in vscode, the imported path has the scope "entity.name.import.go" instead of "comment.line.double-slash.go"

<img width="675" alt="screen shot 2017-05-06 at 6 08 26 pm" src="https://cloud.githubusercontent.com/assets/16890566/25777102/70308c26-3287-11e7-9690-9fa65b158c25.png">

**Comment by ramya-rao-a** [comment]
Also, I have the latest Atom (1.15.0). How do I ensure that the latest https://github.com/atom/language-go is being used in the Atom I am using?

**Comment by 50Wliu** [comment]
There's a few ways.
1. You can `apm dev language-go`, and then run Atom using `atom --dev`.
2. You can clone language-go, `apm link` it, and then run Atom as usual (dangerous if you forget to unlink after you're done).
3. You can install it as a git package by pasting the repository URL into the Install section of the Settings View.

**Comment by ramya-rao-a** [comment]
thanks @50Wliu

**Comment by ramya-rao-a** [comment]
This is fixed in the latest Insiders build
