### ISSUE TITLE
Multi line string in a var with dot still breaks highlighting for rest of the code

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#120]
See https://github.com/Microsoft/vscode-go/issues/707#issuecomment-297969367

The scope for the text in the second line of the multi line string is "source.go" instead of "string.quoted.raw.go"

Text following the second backtick get the scope "string.quoted.raw.go"

VSCode is using the Go grammar from https://github.com/atom/language-go/commit/6de3f61

**Comment by ramya-rao-a** [comment]
cc @50Wliu

**Comment by 50Wliu** [comment]
```go
var c *a.b = `
	test
`
```
