### ISSUE TITLE
Variables with periods are not tokenized correctly

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#121]
_From @chenhw2 on April 28, 2017 10:1_

```go
type EXAMPLE struct {
	SubNet *net.IPNet
}

var e EXAMPLE
_, e.SubNet, _ = net.ParseCIDR("192.168.0.0/16")
```

![sp170428_175917](https://cloud.githubusercontent.com/assets/12322033/25524266/78fdce50-2c3c-11e7-9c20-2f2895b6fe8b.png)

Front ```_``` different from back ```_```

```
Versions
vscode-go: 0.6.59 - 4th April, 2017
vscode: 1.11.2
ubuntu 16.04
```

_Copied from original issue: Microsoft/vscode-go#950_

**Comment by ramya-rao-a** [comment]
The first `_` is getting the scope "source.go" and the second is getting "variable.other.assignment.go"

VSCode is using the Go grammar from https://github.com/atom/language-go/commit/6de3f61

The same can be seen in atom as well

**Comment by 50Wliu** [comment]
I have a fix for this, but as it seems closely related to #120 I think I'm going to wait until I have a response for that one in order to kill two birds with one stone.
