### ISSUE TITLE
Slice highlighting issue

### ISSUE THREAD

**Issue by joefitzgerald** [atom/language-go#123]
(Moved from https://github.com/joefitzgerald/go-plus/issues/639, originally opened by https://github.com/mkreibe)
 
### Prerequisites

* [x] Have you tried launching `atom .` from the terminal in your project's directory?
* [x] Have you verified the output from `go env` is correct? If it is, please include the output in this issue.
* [x] Have you updated Atom to the latest version?
* [ ] Have you tried using [Atom Beta](https://atom.io/beta), which can be run side-by-side with Atom Stable? Is the behavior the same, or different?
* [x] Have you updated your Atom packages to the latest versions?
* [x] Have you read the [FAQ](https://github.com/joefitzgerald/go-plus/wiki/FAQ)?
* [x] Have you searched [the issues](https://github.com/joefitzgerald/go-plus/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if others are experiencing the same issue?

### Description

Currently slices hightlight correctly... This is NOT about slices. Arrays do not highlight correctly:

I totally understand this is a minor issue.

### Expected Behavior
```go
var myArray [5]int // these should highlight 
var myArray [...]int
```
### Actual Behavior
```go
var myArray [5]int // Doesn't highlight
var myArray [...]int // Nor does this.
var mySlice []int // works just fine
```

**Comment by 50Wliu** [comment]
`var myArray [5]int // Doesn't highlight` has been fixed.
