### ISSUE TITLE
Inconsistent syntax highlighting for multiple assignment to fields

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#128]
_From @willfaught on May 11, 2017 23:37_

See the attached image:

<img width="519" alt="screen shot 2017-05-11 at 11 46 04 am" src="https://cloud.githubusercontent.com/assets/63830/25976180/1254e39c-3668-11e7-9845-762829e5809c.png">

The FieldsSplit field is colored differently than the other fields in the assignment.

_Copied from original issue: Microsoft/vscode-go#992_

**Comment by ramya-rao-a** [comment]
In the above case `FieldsSplit` gets the scope `variable.other.assignment.go` and rest of the words before it get `source.go`

**Comment by 50Wliu** [comment]
Cannot reproduce on f9a27ad:
![image](https://cloud.githubusercontent.com/assets/2766036/26428192/5b8af3ee-40ae-11e7-8b4b-0e9fa3806f76.png)

**Comment by ramya-rao-a** [comment]
Thanks @50Wliu I can confirm that this is fixed in the latest grammar as well
