### ISSUE TITLE
Variable block declaration syntax highlighting broken by call assignment

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#130]
_From @willfaught on July 8, 2017 0:8_

Can be seen with this syntax:

```go
var (
	AAA = foo() // AAA is correctly light blue
	BBB string  // BBB is incorrectly white; it should be light blue like AAA
)
```

*Note: GitHub syntax highlighting for the above doesn't show the problem.*

See the screenshot:

![screen shot 2017-07-07 at 5 04 33 pm](https://user-images.githubusercontent.com/63830/27980711-8c6333c8-6336-11e7-85b4-f5cd2fdf0e7f.png)

VS Code: Version 1.13.1 (1.13.1), 379d2efb5539b09112c793d3d9a413017d736f89
OS: macOS Sierra 10.12.5 (16F73)

_Copied from original issue: Microsoft/vscode-go#1071_

**Comment by ramya-rao-a** [comment]
@50Wliu Another `var` and `()` issue.

This must be a regression. I cannot repro in Atom 1.18.0. But I can repro when using `atom --dev` after running `apm dev language-go`

**Comment by ramya-rao-a** [comment]
VS Code is using the version https://github.com/atom/language-go/commit/c1fe618ccf2dcd17118c5600c49b1c539f26d5c5

**Comment by 50Wliu** [comment]
This one might be a bit tricky.

**Comment by ramya-rao-a** [comment]
@50Wliu  May I just say that you are our grammar champion :)

I have lost the count of the number of times I have moved a grammar related bug to this repo and you have fixed it.

I wanted to thank you for all your work and I really appreciate everything you do 👏
