### ISSUE TITLE
highlighting: nested field accesses colored inconsistently

### ISSUE THREAD

**Issue by ramya-rao-a** [atom/language-go#135]
_From @willfaught on August 19, 2017 8:26_

Steps to Reproduce:

1. Enter into a function:

```go
a.b = 1
a.b.c = 2
a.b.c.d = 3
a.b.c.d.e = 3
```

2. See the following inconsistent field accessor syntax highlighting:

<img width="175" alt="screen shot 2017-08-19 at 1 21 38 am" src="https://user-images.githubusercontent.com/63830/29484886-3def6456-847d-11e7-869f-4b8bf83414cb.png">

_Copied from original issue: Microsoft/vscode#32820_

**Comment by ramya-rao-a** [comment]
_From @mjbvz on August 19, 2017 19:3_

@willfaught That is go code, correct?

**Comment by ramya-rao-a** [comment]
_From @willfaught on August 19, 2017 19:5_

Yes

**Comment by ramya-rao-a** [comment]
The blue ones have the scope `variable.other.assignment.go`
The white ones have the scope `source.go`.

The color issue occurs in Atom as well

**Comment by 50Wliu** [comment]
I have a fix for this.  However, it's more of a temporary one.  I'd like to understand what the `.` operator stands for in Go: is it more-or-less the same as `obj.property` and `obj.method()` in say, JS or Java?

**Comment by willfaught** [comment]
@wliu Yep
