### ISSUE TITLE
Syntax color of declared identifiers changes if type is present

### ISSUE THREAD

**Issue by willfaught** [atom/language-go#140]
In a const block, if a declaration is explicitly typed, the name is white, but if not, then it's light blue:

![screen shot 2017-09-27 at 3 04 38 pm](https://user-images.githubusercontent.com/63830/30940251-4979307c-a395-11e7-9cc9-d1fe1ef08c5b.png)

This can look strange:

![screen shot 2017-09-27 at 3 09 01 pm](https://user-images.githubusercontent.com/63830/30940400-d5234388-a395-11e7-8c54-40471033c6f0.png)

![screen shot 2017-09-27 at 3 13 12 pm](https://user-images.githubusercontent.com/63830/30940597-6e35802c-a396-11e7-8884-a478702c69bf.png)

Note that the syntax highlighting for variables is consistent in this case:

![screen shot 2017-09-27 at 3 16 10 pm](https://user-images.githubusercontent.com/63830/30940722-ebb64b26-a396-11e7-9c27-72ab11d03050.png)
![screen shot 2017-09-27 at 3 16 23 pm](https://user-images.githubusercontent.com/63830/30940723-ebbe7242-a396-11e7-8385-2a9c3b6e36e1.png)

I don't use Atom, this was observed in vscode. If all that issue prerequisite stuff is still required in that case, then let me know and I can move this issue to the vscode-go repo.

(@ramya-rao-a)

**Comment by ramya-rao-a** [comment]
In the above cases, the declarations in blue have the scope `variable.other.assignment.go` and the one in white has the scope `source.go`

Same issue occurs in Atom as well
