### ISSUE TITLE
Some keywords are not hightlited when i use tree-sitter. 

### ISSUE THREAD

**Issue by purpuregecko** [atom/language-go#148]
I'm not sure this is right place to submit this issue. But I think problem in [this](https://github.com/atom/language-go/blob/master/grammars/tree-sitter-go.cson) file.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

defer, range, interface, goto, fallthrough keywords not hightlited using tree-sitter

### Steps to Reproduce

1. Install 1.25.0-beta0
2. Enable tree-sitter
3. write code using this keywords

**Expected behavior:**

highlited like if, for and other

**Actual behavior:** 

not highlited

**Reproduces how often:**

always

### Versions

atom-beta --version
Atom    : 1.25.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

Maybe I miss something. [List of keywords.](https://golang.org/ref/spec#Keywords)

**Comment by maxbrunsfeld** [comment]
Thanks for the report @purpuregecko. I've added the missing keywords. I'm still not seeing `fallthrough` get highlighted. I think this is because of a bug in the core syntax highlighting system in Atom. I'll fix this shortly.

**Comment by maxbrunsfeld** [comment]
Oh, nevermind. The issue with `fallthrough` was due to a difference in the way `fallthrough_statement` was parsed compared to the other statements with keywords. Fixed in https://github.com/tree-sitter/tree-sitter-go/commit/68b556dc178076c0decc2b7cf3561db37f6f960f.
