### ISSUE TITLE
Cannot fold up a continuous comment-out code

### ISSUE THREAD

**Issue by Toasa** [atom/language-go#165]
### Description

When a comment-out code is continuous multi lines, I cannot fold up such that code.
My atom version is 1.32.1 and "language-go", that is core package, is 0.46.4.
I remember that I can fold the comment-out previous "atom" and "language-go" version.

### Steps to Reproduce

Write a multiple line comment-out code e.g.:

```go
// hello
// world
// comment
```

**Expected behavior:**

Be able to fold up the some continuous comment-out codes to one line code.

**Actual behavior:**
cannot fold up.

**Reproduces how often:**
Everytime after update atom and language-go(core package)

### Versions
atom: 1.32.1
language-go(core package) : 0.46.4

**Comment by ankita55** [comment]
+1
This is a very handy feature. It disappeared suddenly.  Please fix this soon.
Atom version: 1.32.2

**Comment by rsese** [comment]
Thanks for the report - looks like the same issue as reported for JavaScript x-ref: https://github.com/atom/language-javascript/issues/607.

Reproduced in 1.34.0-nightly12 on macOS 10.12.6.

**Comment by ankita55** [comment]
Thanks a ton @rsese . This is exactly what I was looking for!

**Comment by rsese** [comment]
Thanks again for the report - since this affects multiple languages, we created an issue in atom/atom for tracking if you want to subscribe there:

https://github.com/atom/atom/issues/18549
