### ISSUE TITLE
No autocomplete for certain langauge keywords like `return` or `break` etc

### ISSUE THREAD

**Issue by rajalokan** [atom/language-go#171]
### Description
At present auto suggestion for language keywords like `return`, `break` etc isn't working for a go file. Having to quickly select suggested word beneath cursor is very handy most of the time.

### Steps to Reproduce

1. Create a go file and open it in atom. 
2. In any function try writing `return` statement.
3. You will find there is no suggestion till I have to write complete word.

**Expected behavior:** 

Would like how it is auto suggested for a python file as below 
![py](https://user-images.githubusercontent.com/1624307/57225118-061c5180-7029-11e9-9912-035a20e13087.png)
 
**Actual behavior:** 

![noautosuggestion](https://user-images.githubusercontent.com/1624307/57225134-1c2a1200-7029-11e9-9c85-2ec8027499a6.png)

**Reproduces how often:** 

Always

### Versions
```
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
Running on Ubuntu-18.04.

### Additional Information
Not needed.

**Comment by rsese** [comment]
Thanks for reaching out!  As mentioned in the README, this package only provides syntax highlighting and snippets for Go.  I'm assuming you have some community package that provides Python autocompletion?  If you want Go specific autocompletion and completions beyond the built-in autocomplete provider, you'll need to install a community package that provides Go autocompletion (I don't use Go myself but saw this package for example https://github.com/joefitzgerald/go-plus).
