### ISSUE TITLE
Weird Highlighting on returns

### ISSUE THREAD

**Issue by tombell** [atom/language-go#22]
Highlighting is a bit off when returning:

![screen shot 2014-05-26 at 22 47 58](https://cloud.githubusercontent.com/assets/129327/3085964/bdff7a88-e51f-11e3-8ec5-0e733c71d444.png)

**Comment by myusuf3** [comment]
I want to use Atom but the go syntax highlighting is so bad. Is there anything else we can use?

**Comment by svanharmelen** [comment]
@myusuf3 maybe you could point out what exactly it is that you find so bad? As personally I'm quite happy with the syntax highlighting, so I'm curious what you find so bad about it.

As far as I know this is the only Go language package for Atom. Please do note that the highlighting itself is not done is this package! It's done based on the classes assigned to the code/text by this package, but there are separate packages for Atom theme's and the highlighting.

**Comment by svanharmelen** [comment]
@tombell can you confirm this one can be closed? I believe the issues are solved, but would be nice if you can confirm that :smiley:

**Comment by myusuf3** [comment]
@svanharmelen That was I am talking about some of the choices made here with regard to classes I dont like. This is mostly aesthetics take a look at Sublime Text classes for reference for what I prefer. 

Made a huge difference and reason I went back to sublime.

**Comment by tombell** [comment]
@svanharmelen I don't actually use Atom anymore.

**Comment by svanharmelen** [comment]
@tombell check... Thanks for letting me know, I will close this one then. If in the future your willing to give Atom another go and have some issues, by all means please open up a new issue again!

@myusuf3 the same goes for you of course! If you ever get back to trying Atom and have issues, just open a new issue with as much concrete examples as possible so we can try to work to out a solution.

Cheers...
