### ISSUE TITLE
HTML template support

### ISSUE THREAD

**Issue by mfhholmes** [atom/language-go#26]
It'd be great if Atom supported html templates like SublimeText does, and could differentiate between the Go template instructions and the html (and tell me when I've messed up either).

Two wrinkles:
- extension: there's no defined extension for html templates. I use "gohtml" because I wanted to differentiate between html and text templates, but I've seen others use ".tmp" and ".tmpl" too.
- delimiters: the default is {{...}}, but if you're using a client-side library that also uses them (like Angular.js) then you can change the delimiter in the template (I use [[...]] for this reason).
It'd be great if there was a way of specifying extension and delimiter in the settings somehow.

Not an issue, just a feature request. And reposted from the go-plus repo.

**Comment by svanharmelen** [comment]
@mfhholmes if I'm not mistaking this is fixed by #30 right? Can you confirm this can be closed?

**Comment by mfhholmes** [comment]
Yep all good :)

-- 
  Marcus Holmes
  @Gentlemantech
  0466 564660
  mh@marcusholmes.biz

**Comment by svanharmelen** [comment]
Check... Thanks!
