### ISSUE TITLE
weird indenting with nested functions

### ISSUE THREAD

**Issue by ZehCnaS34** [atom/language-go#31]
When declaring a function as an argument, the trailing curly brace is not properly placed. Is this a problem with this package, or the core text buffer and how it handles indents? Reason I ask is because
I experience the same problem with other languages.

Before gofmt
![bad](https://cloud.githubusercontent.com/assets/1127553/6062034/8e712de8-ad1a-11e4-91ee-fe55bc9cb0eb.png)

After gofmt
![good](https://cloud.githubusercontent.com/assets/1127553/6062033/8c6d2aa6-ad1a-11e4-9f5f-bdfe048e37ff.png)

**Comment by kevinsawicki** [comment]
So the first screenshot is how it is behaving currently? And the second one is how it should be?

**Comment by nathany** [comment]
presumably. I think the second is what you would get after running gofmt.

**Comment by ZehCnaS34** [comment]
Yeah, the second one is after gofmt.

**Comment by svanharmelen** [comment]
@ZehCnaS34 this seems (indeed) to be related to Atom core and not to this particular package. But I think in Atom (at least) version 0.190.0 this is fixed as I cannot reproduce this problem...
