### ISSUE TITLE
Weird highlighting with type

### ISSUE THREAD

**Issue by yelfathi** [atom/language-go#32]
Hi,

In this example we can see that we have the same color the user-defined (Myfloat) type and the type itself (float64):
![screenshot 2015-02-19 22 57 50](https://cloud.githubusercontent.com/assets/9952320/6276965/e39c6b7c-b88a-11e4-9a22-4cf1b0425923.png)

It should have the same solor for type and float64. I tried with different syntax themes.

Thanks!

**Comment by bassu** [comment]
@yelfathi Very less syntax themes in Atom target Go so syntax highlighing falls back to whatever default styles the theme provides (ugly IMHO).

You can try this one: https://atom.io/themes/solarized-dark-bold-syntax

P.S. I hacked and modded it specifically for Go.

**Comment by svanharmelen** [comment]
@yelfathi this one works pretty well with Go (and after merging https://github.com/kevinsawicki/monokai/pull/42 it will be even better :wink:):

https://atom.io/themes/monokai

**Comment by svanharmelen** [comment]
I think that currently (with the latest version) this should be pretty good now... At least as good and consistent as possible considering that the matching is done based on regex'es and not on Go AST (don't think that's possible without some serious changes to Atom itself)

**Comment by svanharmelen** [comment]
@yelfathi this should be fixed now:

![image](https://cloud.githubusercontent.com/assets/4171547/9070849/2457b146-3af2-11e5-8a33-b6cd33c69d3c.png)

Could you confirm it's working for you as well?

**Comment by joefitzgerald** [comment]
@yelfathi Could you please report back with the latest version of Atom, and let us know if things are working? I will close this for now, and will reopen it if you feel there is still an issue.

**Comment by yelfathi** [comment]
Thanks, it's OK!
