### ISSUE TITLE
Small struct recognition problem

### ISSUE THREAD

**Issue by soygul** [atom/language-go#35]
![image](https://cloud.githubusercontent.com/assets/617171/6868508/7abad44a-d48c-11e4-9e25-2977c65cf4f1.png)

![image](https://cloud.githubusercontent.com/assets/617171/6868524/94ad931a-d48c-11e4-982e-19fbc01c47ff.png)

`User` is a basic `struct` and I'm using it in a map. Both as a pointer or value map, proper struct highlighting fails in a `make` statement.

This could be a duplicate of #32

**Comment by svanharmelen** [comment]
@soygul this should be a lot better now:

![image](https://cloud.githubusercontent.com/assets/4171547/9070200/6b05db8a-3aee-11e5-9d84-b6709b25696b.png)

So can you confirm that this is now fixed (by PR #52)?

**Comment by soygul** [comment]
Will confirm as soon as I get my hands on the latest atom. Thanks for the update!

**Comment by soygul** [comment]
Confirmed to work as expected now and looks very good. Closing this. Thanks.

![image](https://cloud.githubusercontent.com/assets/617171/9081745/4e8fa410-3b5f-11e5-857e-2f77444e0396.png)
