### ISSUE TITLE
built-in functions not matching correctly

### ISSUE THREAD

**Issue by TTBlair** [atom/language-go#37]
My built-in functions (new, len, etc.) don't match properly IF there is only one argument.  The function name matches fine, but the opening parenthesis doesn't seem to match any rule at all, when I inspect it there is no markup around the parenthesis at all, so my syntax theme doesn't color it, leaves it white.  The parameter inside the parentheses is marked as class="storage type go", which I don't think is correct either.  The last parenthesis seems to marked correctly as class="keyword operator bracket go".

![go-lang-grammar](https://cloud.githubusercontent.com/assets/8835337/7010460/08ede7d4-dc67-11e4-909d-b46466a39480.gif)

**Comment by svanharmelen** [comment]
@TTBlair I cannot reproduce this with the latest version... Likely PR #36 fixed this problem. Could you maybe update to the latest version and test/try again?

**Comment by TTBlair** [comment]
@svanharmelen, that fixed it right up.  I didn't realize I was on an older version, thanks so much!
