### ISSUE TITLE
Formatting error for switch statement

### ISSUE THREAD

**Issue by Astarry** [atom/language-go#41]
When I start a switch stmt, the case keywords are not inserted at the correct indentation. Sublime text seems to correct the indentation for case stmt when the : is inserted.

**Comment by svanharmelen** [comment]
Noticed that as well... And also had another look at issue #31 so was already working on fixing this, but think we need a tweak in Atom core as well as in this package... Will update when I have something working.

**Comment by svanharmelen** [comment]
@Astarry there have been a few nice improvements around indenting and as far as I can see this should be working as expected now. Can you confirm your issue is solved now (using Atom 1.0.3 and the latest `language-go` package)?

**Comment by 50Wliu** [comment]
Closing as no feedback has been provided and the issue should have been fixed.
