### ISSUE TITLE
Snippets could be bundled in a separate (optional) package

### ISSUE THREAD

**Issue by mdwhatcott** [atom/language-go#61]
When starting out with Atom and go development the snippets in this package got in the way of regular every-day typing. I still trip over them unintentionally at times and I'd like to see them extracted to a separate, optional package.

Thoughts?

**Comment by mdwhatcott** [comment]
Nevermind, it seems that all of the `language-xx` plugins are bundled with snippets. It probably doesn't make sense to separate the snippets in this package unless all other such package get the same treatment. I'll just overwrite the snippets that get in the way.

**Comment by svanharmelen** [comment]
@mdwhatcott I don't think that's needed. I assume (could be wrong of course) that you mean you accidentally trip over them as they are suggested by the `autocomplete-plus` package?

If that is the case, you can turn that behaviour off by disabling the `autocomplete-snippets` package. Or if you really don't want any snippets related behaviour, you could also disable the `snippets` package.

Hope that helps....
