### ISSUE TITLE
labeled statements interfere with code folding

### ISSUE THREAD

**Issue by carstn** [atom/language-go#65]
A [labeled statement](https://golang.org/ref/spec#Labeled_statements) is treated as a Level 1 block (because gofmt will de-indent labels). As a result, folding a function that contains a labeled statement will not be fully folded - only the code preceding the label folds.

I'd expect the function to fold completely, disregarding labeled statements.

For an example, copy this code chunk into Atom and fold line 10 (the `gitDir()` function): 
```go
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

// gitRoot finds the nearest directory containing `.git` above the current working directory.
func gitRoot() (dir string, err error) {
	if dir, err = os.Getwd(); err != nil {
		return
	}

DirectoryCheck:
	for {
		dir = filepath.Dir(dir)
		if len(dir) < 2 {
			err = fmt.Errorf("Error: unable to find root of git directory. %q", dir)
			return
		}

		var tempDir *os.File
		if tempDir, err = os.Open(dir); err != nil {
			return
		}
		var filenames []string
		if filenames, err = tempDir.Readdirnames(0); err != nil {
			return
		}
		for _, file := range filenames {
			if file == ".git" {
				break DirectoryCheck
			}
		}
	}

	return
}

func main() {
	dir, _ := gitRoot()
	fmt.Println(dir)
}
```

**Comment by 50Wliu** [comment]
This is due to a limitation in Atom where code-folding is solely indentation-based: please see atom/atom#3442 for more details.
