### ISSUE TITLE
Comments not highlighted properly inside var blocks

### ISSUE THREAD

**Issue by derekperkins** [atom/language-go#73]
Comments inside of var blocks are highlighted as code, not as comments.
```
var (
	// returns map[integrationID]campaignRankings and map[integrationID]rankings.ActivityLog
	CampaignAddWithTx = campaignAddWithTx

	// CampaignDeleteWithTx puts a timestamp in the 'Deleted' field to soft delete the data for the given integrationIDs
	CampaignDeleteWithTx = campaignDeleteWithTx

	// CampaignRollupJSON returns *json.RawMessage
	CampaignRollupJSON = campaignRollupJSON
)
```

![image](https://cloud.githubusercontent.com/assets/3588778/11483895/519baac2-9768-11e5-8a3f-639b22703075.png)

**Comment by svanharmelen** [comment]
Please see closed issues #66, #69 or #72... They all report this problem which was fixed in PR #67 :wink:

So just run `apm install language-go` to get the latest version, or wait until the next minor release of Atom (v1.3.0) which includes the latest version.

**Comment by derekperkins** [comment]
Sorry for the duplicate issue.

**Comment by svanharmelen** [comment]
No worries!
