### ISSUE TITLE
Inconsistent highlighting on slices

### ISSUE THREAD

**Issue by arussellsaw** [atom/language-go#75]
I'm finding that slices are not highlighted correctly depending on the declaration

fairly terse bug report, but not much else to say!

![screen shot 2015-12-02 at 11 32 57](https://cloud.githubusercontent.com/assets/5236823/11530201/ae2c7090-98ea-11e5-943a-593fd582ce43.png)

**Comment by kmckelvin** [comment]
+1 I'm seeing this too

**Comment by JormaSnow** [comment]
Seeing the same thing, also var names showing up either gray or red depending on context; types showing up purple, grey or green depending. etc. haven't taken the time to catalog them all yet for a but report.
Using "One Dark" syntax theme.

**Comment by svanharmelen** [comment]
Fixed in version v0.41.0
