### ISSUE TITLE
main package

### ISSUE THREAD

**Issue by patbaker82** [atom/language-go#81]
Small nitpick.  Anytime creating `package main` I'm always hit with the `main` autocomplete

Usually it turns out like this:

```go
package func main() { 
}
```

**Comment by vsysoev** [comment]
+1

**Comment by patbaker82** [comment]
Not sure the best way to resolve this.  It doesn't look like you can stop snippet evaluation.  I think the best option is to just remove main as a snippet keyword.

Either remove main completely or change it to funcm

Thoughts?  I'm happy to submit a pull request.

**Comment by zmb3** [comment]
I agree with just removing main as a snippet.  Every time I start a new app this bytes me not once but twice.

I type `package main` which gets turned into

```
package func main() {

}
```

After I fix that, I type `func main`, which gets turned into 

```
func func main() {

}
```

It would be great if snippets could be suppressed when `main` is already preceded by `package` or `func` (in this case you're already 90% of the way there and the snippet causes more harm than good), but if this isn't possible just removing the snippet would sure make things easier for me.

**Comment by joefitzgerald** [comment]
This annoys the heck out of me also. What if we modified the snippet to print out the package statement and the main function all at the same time?

**Comment by zmb3** [comment]
That would be an improvement, but still wouldn't fix the problem entirely.  For people that are accustomed to typing `package main` (which I think is most people), we'd end up getting:

```
package package main

func main() {

}
```

Maybe we change the snippet to `pm` instead of `main` so that users who type `package main` won't get hit with this?

**Comment by joefitzgerald** [comment]
What if we made the snippet `packagemain`?

**Comment by patbaker82** [comment]
There is already a snippet for `pkg`.

I suggest:

- Remove main as a snippet prefix
- Create snippet prefix `pkgm` that will create both the package main designaton and the main function

`pkgm`

```go
package main

func main() {

} 
```
