### ISSUE TITLE
Go starter template snippet

### ISSUE THREAD

**Issue by kevindeleon** [atom/language-go#82]
I have a snippet that I use constantly when starting a Go script/package and thought I'd get some opinions on whether or not it might be useful to add into the `language-go` package snippets.

```
'.source.go':
  'go template':
    'prefix': 'got'
    'body': """
      package ${1:main}

      import (
        "${2:fmt}"
      )

      func ${1:main}() {
          $3
      }
    """
```

If you guys think it's worthwhile, let me know and I'll add it to `snippets.cson` and submit a pull-request.

**Comment by svanharmelen** [comment]
Looks fine to me... So just go ahead and make a PR for it :)
