### ISSUE TITLE
Function arguments ending with lowercase word `type` break syntax highlighting for data type

### ISSUE THREAD

**Issue by codyopel** [atom/language-go#91]
![screenshot from 2016-04-04 18-10-31](https://cloud.githubusercontent.com/assets/5561189/14265837/dd7fcece-fa91-11e5-99dd-f305de11b992.png)

Syntax highlighting for the data type for Vartype breaks because it ends in a with a lower cased  word `type` in the name.  The issue only occurs if the entry ends with `type`, if it is in the beginning or middle everything works as expected.

**Comment by 50Wliu** [comment]
On my list.  Will require a large refactoring though.
