### ISSUE TITLE
Multiline raw string highlighting after `var` declarations

### ISSUE THREAD

**Issue by imipolexg** [atom/language-go#94]
Somehow the grammar is broken for multiline raw strings if they come after an old-style type declaration. Open up this [gist](https://gist.github.com/imipolexg/aeec2bb12fd1adae0cd27e865248bb8c) in atom.io to see the bug. The string declared `fooStr :=` with a multiline raw string highlights correctly, but a string declared like `var foo string =` with a multiline raw string ends up highlighting the rest of the buffer (until another ` is encountered).

**Comment by 50Wliu** [comment]
Closing in favor of #103.
